{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-expression",
    "version": "6.2.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.17"
          }
        }
      ],
      "files": [
        {
          "name": "spring-expression-6.2.17.jar",
          "url": "spring-expression-6.2.17.jar",
          "size": 317788,
          "sha512": "f9479ce0fedcf28095a284c216fb6e4d40baae68e24f42aa1f24277f9a3b38cdd294878e46fad0e55a62b532b89649d8256659bbf4d0b3ad132a51787db6e424",
          "sha256": "2c29c8b1099e2cf9c762c1ee6247f0bd2c58ffbc560f16cd872caacd8be27d49",
          "sha1": "d2f104d59e9a2d70c7f55c50c79417a63a24ad86",
          "md5": "8ef5556491d0db1130608070edfbde07"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.17"
          }
        }
      ],
      "files": [
        {
          "name": "spring-expression-6.2.17.jar",
          "url": "spring-expression-6.2.17.jar",
          "size": 317788,
          "sha512": "f9479ce0fedcf28095a284c216fb6e4d40baae68e24f42aa1f24277f9a3b38cdd294878e46fad0e55a62b532b89649d8256659bbf4d0b3ad132a51787db6e424",
          "sha256": "2c29c8b1099e2cf9c762c1ee6247f0bd2c58ffbc560f16cd872caacd8be27d49",
          "sha1": "d2f104d59e9a2d70c7f55c50c79417a63a24ad86",
          "md5": "8ef5556491d0db1130608070edfbde07"
        }
      ]
    }
  ]
}
