{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-webmvc",
    "version": "6.2.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.2.17"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.17"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.17"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.17"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.2.17"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.2.17"
          }
        }
      ],
      "files": [
        {
          "name": "spring-webmvc-6.2.17.jar",
          "url": "spring-webmvc-6.2.17.jar",
          "size": 1094032,
          "sha512": "7b222f110609026940326ed33ed51a1c203a3f557625b4e6f26e29646888a1eac9d8edb289f33c0408c1d6f9bb15c3151b9dd59b65dbe730b628990508869b9c",
          "sha256": "8d7a27fa7fc6ae42cced2bc415355de9172607a1b5bdd7793c04ecd856230424",
          "sha1": "5c49b782703377274dd1e1405825fa2cd0ca4d8b",
          "md5": "93805593c6b65aabe1c69728b69925fa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.2.17"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.17"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.17"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.17"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.2.17"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.2.17"
          }
        }
      ],
      "files": [
        {
          "name": "spring-webmvc-6.2.17.jar",
          "url": "spring-webmvc-6.2.17.jar",
          "size": 1094032,
          "sha512": "7b222f110609026940326ed33ed51a1c203a3f557625b4e6f26e29646888a1eac9d8edb289f33c0408c1d6f9bb15c3151b9dd59b65dbe730b628990508869b9c",
          "sha256": "8d7a27fa7fc6ae42cced2bc415355de9172607a1b5bdd7793c04ecd856230424",
          "sha1": "5c49b782703377274dd1e1405825fa2cd0ca4d8b",
          "md5": "93805593c6b65aabe1c69728b69925fa"
        }
      ]
    }
  ]
}
